services:
  frontend:
    build: .
    container_name: rtls_frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      
      - BACKEND_URL=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
